vendor: Oracle Linux
name: Oracle Container Services for use with Kubernetes
version: 1.10.5-2.0.2.el7
website_url: https://www.oracle.com/linux/index.html
documentation_url: https://docs.oracle.com/cd/E52668_01/E88884/html/index.html
product_logo_url: https://www.oracle.com/webfolder/s/brand/identity/logo/index.html#primary
type: distribution
description: Kubernetes installer for Oracle Linux
